mysql:
  host: 192.168.1.99
  port: 13306
  user: root
  passwd: Mjolnir
  database: go

redis:
  host: 192.168.1.99
  port: 16379
  passwd: Mjolnir
  db: 1

zap:
  level: info
  logfile: /var/log/go-proj/sys.log
  format: console

cros:
  mode: allow-all  # rule
  whitelist:
    - 192.168.1.230

server:
  host: 0.0.0.0
  port: 9009